# action.yaml
name: 'Kaya Identity Calculation GitHub Action'
description: 'A GitHub Action that takes inputs and returns the Kaya Identity'


runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install packages
      run: pip install .
      shell: bash

    - name: Run unittest
      run: python test_Kaya.py
      shell: bash
