# .github/workflows/test_action.yaml
name: Test Action
on: [push]

jobs:
  get_Kaya_identity:
    runs-on: ubuntu-latest
    name: Returns the Kaya_identity
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Kaya_identity
        id: Kaya_identity
        uses: ./ # Uses an action in the root directory
      - name: Print the success message
        run: echo "CI passed - merging!"
